/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.RemoteDesktop;

/**
 *
 * @author sabbir
 */

import java.awt.Desktop;
import java.io.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class RemoteDesktop extends javax.swing.JFrame {

    /**
     * Creates new form RemoteDesktop
     */
    private int portServerInt=6789;//set port for server
    private int portClientInt=6789;//set port for client
    
    private String portServer="";//server port taken as String
    private String portClient="";//client port taken as String
    private String ipClient="";//client ip Address
    
    private boolean showComp=false;//show or hide computer&contacts
    private ClientMessenger messengerClient;//messenger for client
    private ServerMessenger messengerServer;//messenger for server
    
    static String alias;//username for messenger
    private int showExitDialogue;//exit dialogue box value
    private Scanner file;//file inout
    private BufferedWriter writeFile;//to write in file
    private boolean exitShow=true;//exit box check variable
    
    
    //public static String status="Disconnected";
    
    
    //RemoteDesktop constructor begin
    public RemoteDesktop() {
        initComponents();//initializing components
        
        openFile("alias.log");//open file for alias
        alias=file.next();//read string for alias
        closeFile();//closing file
        
        displayIP();//displaying server ip address
        setStatusTextArea("Ready to connect");//setting connection status
        
        ComputersAndContacts application=new ComputersAndContacts();//create computer and contact
        application.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
          
        
    }//end RemoteDesktop constructor
    
    //method openFile begin
    private void openFile(String fileName)
    {
        try {
            file=new Scanner(new File(fileName));//open file with file name
        }//end try
        catch (FileNotFoundException ex) {
            Logger.getLogger(ComputersAndContacts.class.getName()).log(Level.SEVERE, null, ex);
        }//end catch
    }//end method openFile()
    
    //method closeFile begin
    private void closeFile()
    {
        if(file!=null)
        {
            file.close();//file closed
        }
    }//end method closeFile()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainFrame = new javax.swing.JFrame();
        ExitDialog = new javax.swing.JDialog();
        exitLabel = new javax.swing.JLabel();
        exitCheckBox = new javax.swing.JCheckBox();
        exitButton = new javax.swing.JButton();
        cancelExitButton = new javax.swing.JButton();
        settingsFrame = new javax.swing.JFrame();
        settingsOKButton = new javax.swing.JButton();
        settingsPane = new javax.swing.JTabbedPane();
        generalPanel = new javax.swing.JPanel();
        aliasLabel = new javax.swing.JLabel();
        aliasField = new javax.swing.JTextField();
        exitDialogueBox = new javax.swing.JCheckBox();
        whiteListPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        whiteListTextArea = new javax.swing.JTextArea();
        blackListPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        blackListTextArea = new javax.swing.JTextArea();
        about = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        yourInformationPanel = new javax.swing.JPanel();
        userNameLabelYourInformation = new javax.swing.JLabel();
        portLabelYourInformation = new javax.swing.JLabel();
        portTextFieldYourInformation = new javax.swing.JTextField();
        setButtonYourInformation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ipTextArea = new javax.swing.JTextArea();
        serverMessengerButton = new javax.swing.JButton();
        partnerPanel = new javax.swing.JPanel();
        serverIPLabelClient = new javax.swing.JLabel();
        serverIPTextFieldClient = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();
        serverPortTextFieldClient = new javax.swing.JTextField();
        serverPortLabelClient = new javax.swing.JLabel();
        clientMessengerButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        statusTextArea = new javax.swing.JTextArea();
        compButton = new javax.swing.JButton();
        namePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBarMainFrame = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        seperatorFileMenu = new javax.swing.JPopupMenu.Separator();
        exitFileItem = new javax.swing.JMenuItem();
        optionMenu = new javax.swing.JMenu();
        settingsItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpHelpItem = new javax.swing.JMenuItem();
        aboutHelpItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout MainFrameLayout = new javax.swing.GroupLayout(MainFrame.getContentPane());
        MainFrame.getContentPane().setLayout(MainFrameLayout);
        MainFrameLayout.setHorizontalGroup(
            MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        MainFrameLayout.setVerticalGroup(
            MainFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        exitLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        exitLabel.setText("Are you sure to exit?");

        exitCheckBox.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        exitCheckBox.setText("Don't ask me again");
        exitCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitCheckBoxActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        cancelExitButton.setText("Cancel");
        cancelExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExitDialogLayout = new javax.swing.GroupLayout(ExitDialog.getContentPane());
        ExitDialog.getContentPane().setLayout(ExitDialogLayout);
        ExitDialogLayout.setHorizontalGroup(
            ExitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitDialogLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelExitButton)
                .addGap(33, 33, 33))
            .addGroup(ExitDialogLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(ExitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitCheckBox)
                    .addComponent(exitLabel))
                .addContainerGap())
        );

        ExitDialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelExitButton, exitButton});

        ExitDialogLayout.setVerticalGroup(
            ExitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(exitCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ExitDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(cancelExitButton))
                .addContainerGap())
        );

        ExitDialogLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelExitButton, exitButton});

        settingsFrame.setTitle("Settings");
        settingsFrame.setResizable(false);

        settingsOKButton.setText("OK");
        settingsOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsOKButtonActionPerformed(evt);
            }
        });

        settingsPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        settingsPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        settingsPane.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        generalPanel.setBackground(new java.awt.Color(255, 255, 255));

        aliasLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aliasLabel.setText("Set Alias: ");

        aliasField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        exitDialogueBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        exitDialogueBox.setText("Show exit dialogue box");
        exitDialogueBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitDialogueBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addComponent(aliasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aliasField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exitDialogueBox))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aliasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aliasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(exitDialogueBox)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        settingsPane.addTab("General", generalPanel);

        whiteListPanel.setBackground(new java.awt.Color(255, 255, 255));

        whiteListTextArea.setColumns(20);
        whiteListTextArea.setRows(5);
        jScrollPane3.setViewportView(whiteListTextArea);

        javax.swing.GroupLayout whiteListPanelLayout = new javax.swing.GroupLayout(whiteListPanel);
        whiteListPanel.setLayout(whiteListPanelLayout);
        whiteListPanelLayout.setHorizontalGroup(
            whiteListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        whiteListPanelLayout.setVerticalGroup(
            whiteListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );

        settingsPane.addTab("White List", whiteListPanel);

        blackListPanel.setBackground(new java.awt.Color(255, 255, 255));

        blackListTextArea.setColumns(20);
        blackListTextArea.setRows(5);
        jScrollPane4.setViewportView(blackListTextArea);

        javax.swing.GroupLayout blackListPanelLayout = new javax.swing.GroupLayout(blackListPanel);
        blackListPanel.setLayout(blackListPanelLayout);
        blackListPanelLayout.setHorizontalGroup(
            blackListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        blackListPanelLayout.setVerticalGroup(
            blackListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );

        settingsPane.addTab("Black List", blackListPanel);

        javax.swing.GroupLayout settingsFrameLayout = new javax.swing.GroupLayout(settingsFrame.getContentPane());
        settingsFrame.getContentPane().setLayout(settingsFrameLayout);
        settingsFrameLayout.setHorizontalGroup(
            settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingsOKButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(settingsPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        settingsFrameLayout.setVerticalGroup(
            settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsFrameLayout.createSequentialGroup()
                .addComponent(settingsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsOKButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel10.setText("#1005010");

        jLabel12.setText("#1005005");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Ishtiaque Ahmed");

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setText("Credits:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Sabbir Ahmad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel16.setText("BUET");

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel13.setText("Supervisor:");

        jLabel15.setText("Lecturer, CSE");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Masruba Tasnim");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Level-2 Term-1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Java Term Project");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Version 1.0");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel2.setText("Remote Desktop Sharing");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setText("Computer Science & Engineering");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setText("Bangladesh University of Engineering & Technology");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout aboutLayout = new javax.swing.GroupLayout(about.getContentPane());
        about.getContentPane().setLayout(aboutLayout);
        aboutLayout.setHorizontalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        aboutLayout.setVerticalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remote Desktop");
        setResizable(false);

        mainTabbedPane.setBackground(new java.awt.Color(56, 189, 246));
        mainTabbedPane.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        yourInformationPanel.setBackground(new java.awt.Color(56, 189, 246));
        yourInformationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        yourInformationPanel.setPreferredSize(new java.awt.Dimension(468, 20));

        userNameLabelYourInformation.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        userNameLabelYourInformation.setText("Your IP");

        portLabelYourInformation.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        portLabelYourInformation.setText("Port");

        portTextFieldYourInformation.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        portTextFieldYourInformation.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        portTextFieldYourInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portTextFieldYourInformationActionPerformed(evt);
            }
        });

        setButtonYourInformation.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        setButtonYourInformation.setText("Set");
        setButtonYourInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonYourInformationActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ipTextArea.setColumns(20);
        ipTextArea.setEditable(false);
        ipTextArea.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        ipTextArea.setRows(5);
        ipTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(ipTextArea);

        serverMessengerButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        serverMessengerButton.setText("Messenger");
        serverMessengerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverMessengerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout yourInformationPanelLayout = new javax.swing.GroupLayout(yourInformationPanel);
        yourInformationPanel.setLayout(yourInformationPanelLayout);
        yourInformationPanelLayout.setHorizontalGroup(
            yourInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yourInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yourInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(yourInformationPanelLayout.createSequentialGroup()
                        .addGroup(yourInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(portLabelYourInformation, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userNameLabelYourInformation, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(yourInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(portTextFieldYourInformation))
                        .addGap(0, 284, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yourInformationPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(serverMessengerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(setButtonYourInformation)))
                .addContainerGap())
        );

        yourInformationPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, portTextFieldYourInformation});

        yourInformationPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {serverMessengerButton, setButtonYourInformation});

        yourInformationPanelLayout.setVerticalGroup(
            yourInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yourInformationPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(yourInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabelYourInformation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yourInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(portTextFieldYourInformation)
                    .addComponent(portLabelYourInformation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(yourInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setButtonYourInformation)
                    .addComponent(serverMessengerButton)))
        );

        yourInformationPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {portLabelYourInformation, userNameLabelYourInformation});

        yourInformationPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, portTextFieldYourInformation});

        yourInformationPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {serverMessengerButton, setButtonYourInformation});

        mainTabbedPane.addTab("Server", yourInformationPanel);

        partnerPanel.setBackground(new java.awt.Color(56, 189, 246));
        partnerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Server Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        serverIPLabelClient.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        serverIPLabelClient.setText("Server IP");

        serverIPTextFieldClient.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        serverIPTextFieldClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverIPTextFieldClientActionPerformed(evt);
            }
        });

        connectButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        serverPortTextFieldClient.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        serverPortTextFieldClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverPortTextFieldClientActionPerformed(evt);
            }
        });

        serverPortLabelClient.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        serverPortLabelClient.setText("Server Port");

        clientMessengerButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        clientMessengerButton.setText("Messenger");
        clientMessengerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientMessengerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout partnerPanelLayout = new javax.swing.GroupLayout(partnerPanel);
        partnerPanel.setLayout(partnerPanelLayout);
        partnerPanelLayout.setHorizontalGroup(
            partnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, partnerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(partnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(partnerPanelLayout.createSequentialGroup()
                        .addGroup(partnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serverIPLabelClient, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(serverPortLabelClient, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(partnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serverIPTextFieldClient, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(serverPortTextFieldClient))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, partnerPanelLayout.createSequentialGroup()
                        .addGap(0, 293, Short.MAX_VALUE)
                        .addComponent(clientMessengerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        partnerPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {clientMessengerButton, connectButton});

        partnerPanelLayout.setVerticalGroup(
            partnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partnerPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(partnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverIPLabelClient)
                    .addComponent(serverIPTextFieldClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(partnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverPortTextFieldClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverPortLabelClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(partnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectButton)
                    .addComponent(clientMessengerButton))
                .addGap(7, 7, 7))
        );

        partnerPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {serverIPTextFieldClient, serverPortTextFieldClient});

        partnerPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {clientMessengerButton, connectButton});

        mainTabbedPane.addTab("Client", partnerPanel);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        statusTextArea.setBackground(new java.awt.Color(212, 208, 200));
        statusTextArea.setColumns(20);
        statusTextArea.setEditable(false);
        statusTextArea.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        statusTextArea.setRows(5);
        statusTextArea.setBorder(null);
        statusTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(statusTextArea);

        compButton.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        compButton.setText("Computers & Contacts");
        compButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compButtonActionPerformed(evt);
            }
        });

        namePanel.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REMOTE DESKTOP SHARING");
        jLabel1.setFocusable(false);

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jMenuBarMainFrame.setBackground(new java.awt.Color(56, 189, 246));

        fileMenu.setBackground(new java.awt.Color(56, 189, 246));
        fileMenu.setText("Connection");
        fileMenu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fileMenu.add(seperatorFileMenu);

        exitFileItem.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        exitFileItem.setText("Exit");
        exitFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitFileItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitFileItem);

        jMenuBarMainFrame.add(fileMenu);

        optionMenu.setBackground(new java.awt.Color(56, 189, 246));
        optionMenu.setText("Options");
        optionMenu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        settingsItem.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        settingsItem.setText("Settings");
        settingsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsItemActionPerformed(evt);
            }
        });
        optionMenu.add(settingsItem);

        jMenuBarMainFrame.add(optionMenu);

        helpMenu.setBackground(new java.awt.Color(56, 189, 246));
        helpMenu.setText("Help");
        helpMenu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        helpHelpItem.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        helpHelpItem.setText("Help");
        helpHelpItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpHelpItemActionPerformed(evt);
            }
        });
        helpMenu.add(helpHelpItem);

        aboutHelpItem.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        aboutHelpItem.setText("About");
        aboutHelpItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutHelpItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutHelpItem);

        jMenuBarMainFrame.add(helpMenu);

        setJMenuBar(jMenuBarMainFrame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(compButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainTabbedPane)
                    .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compButton))
                .addGap(5, 5, 5))
        );

        mainTabbedPane.getAccessibleContext().setAccessibleName("tab2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // TODO add your handling code here:
        ipClient=serverIPTextFieldClient.getText();//get text from ip text field
        portClient=serverPortTextFieldClient.getText();//get text from port text field
        
        try
        {
            portClientInt=Integer.parseInt(portClient);//convert String to integer
            //System.out.printf("portClientInt= %d\n",portClientInt);
            Client application = new Client(ipClient,portClientInt);//creating client JFrame
            application.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            application.setVisible(false);

            messengerClient=new ClientMessenger(ipClient,portClientInt+1);//thread for messenger
            messengerClient.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            messengerClient.setVisible(false);
        }//end try
        catch(Exception e)
        {
            portClient="";
            //showing error message for wrong port
            JOptionPane.showMessageDialog(partnerPanel, "Please enter valid number.\nRange: 1025-65536","Error!",JOptionPane.ERROR_MESSAGE);
        }//end catch
        
    }//GEN-LAST:event_connectButtonActionPerformed

    private void exitFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitFileItemActionPerformed
        // TODO add your handling code here:
        if(exitShow==true)
        {
            ExitDialog.setSize(300,150);//exit dialog box size
            ExitDialog.setVisible(true);//makes visible
        }//end if
        else
        {
            System.exit(0);//exits program
        }//end else
    }//GEN-LAST:event_exitFileItemActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void cancelExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelExitButtonActionPerformed
        // TODO add your handling code here:
        ExitDialog.setVisible(false);
    }//GEN-LAST:event_cancelExitButtonActionPerformed

    private void portTextFieldYourInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portTextFieldYourInformationActionPerformed
        // TODO add your handling code here:
        String port="";
        
        //get port of server as String
        if(evt.getSource()==portTextFieldYourInformation){
            port=String.format("%s",evt.getActionCommand());
            portServer=port;
        }
        
        try
        {
            portServerInt=Integer.parseInt(portServer);//convert String to integer
            //System.out.printf("portServerInt= %d\n",portServerInt);
        }//end try
        catch(Exception e)
        {
            portServer="";
            //showing error message for wrong port
            JOptionPane.showMessageDialog(partnerPanel, "Please enter valid number.\nRange: 1025-65536","Error!",JOptionPane.ERROR_MESSAGE);
        }//end catch
        
    }//GEN-LAST:event_portTextFieldYourInformationActionPerformed

    private void setButtonYourInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonYourInformationActionPerformed
        // TODO add your handling code here:
        portServer=portTextFieldYourInformation.getText();
        try
        {
            portServerInt=Integer.parseInt(portServer);//convert String to integer
            //System.out.printf("portServerInt= %d\n",portServerInt);
            Server application = new Server(portServerInt);//creating server JFrame
            application.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            application.setVisible(true);
        
            try {
                messengerServer = new ServerMessenger(portServerInt+1);//thread for messenger
                messengerServer.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                messengerServer.setVisible(false);
            }//end try 
            catch (IOException ex) {
                Logger.getLogger(RemoteDesktop.class.getName()).log(Level.SEVERE, null, ex);
            }//end catch
        }//end try
        catch(Exception e)
        {
            portServer="";
            //showing error message for wrong port
            JOptionPane.showMessageDialog(partnerPanel, "Please enter valid number.\nRange: 1025-65536","Error!",JOptionPane.ERROR_MESSAGE);
        }//end catch
    }//GEN-LAST:event_setButtonYourInformationActionPerformed

    private void serverPortTextFieldClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverPortTextFieldClientActionPerformed
        // TODO add your handling code here:
        String port="";
        
        //get port from client as String
        if(evt.getSource()==serverPortTextFieldClient){
            port=String.format("%s",evt.getActionCommand());
            portClient=port;
        }
        try
        {
            portClientInt=Integer.parseInt(portClient);//convert String to integer
            //System.out.printf("portClientInt= %d\n",portClientInt);
        }//end try
        catch(Exception e)
        {
            portClient="";
            //showing error message for wrong port
            JOptionPane.showMessageDialog(partnerPanel, "Please enter valid number.\nRange: 1025-65536","Error!",JOptionPane.ERROR_MESSAGE);
        }//end catch
    }//GEN-LAST:event_serverPortTextFieldClientActionPerformed

    private void serverIPTextFieldClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverIPTextFieldClientActionPerformed
        // TODO add your handling code here:
        //get port from client as String
        if(evt.getSource()==serverIPTextFieldClient){
            ipClient=String.format("%s",evt.getActionCommand());
        }
    }//GEN-LAST:event_serverIPTextFieldClientActionPerformed

    private void settingsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsItemActionPerformed
        // TODO add your handling code here:
        openFile("alias.log");//open file to read alias
        alias=file.next();//read string for alias
        closeFile();//closes file
        
        openFile("exitDialogue.log");//open file to check exit box condition
        showExitDialogue=file.nextInt();//read int value 1-for show, 0-for hide
        closeFile();//closes file
        
        whiteListTextArea.setText(null);//clears the text area
        openFile("whitelist.log");//read whitelist
        while(file.hasNext())
        {
            whiteListTextArea.append(file.next()+"\n");//white list contacts appending to textarea
        }//end while
        closeFile();//closes file
        
        blackListTextArea.setText(null);//clears text area
        openFile("blacklist.log");//read black list
        while(file.hasNext())
        {
            blackListTextArea.append(file.next()+"\n");//black list contacts appending to textarea
        }
        closeFile();
        
        aliasField.setText(alias);//shows alias
        if(showExitDialogue==1)//check to show checkbox enabled or not
        {
            exitDialogueBox.setSelected(true);//sets checkbox selected
        }
        else
        {
            exitDialogueBox.setSelected(false);//sets checkbox diselected   
        }
        
        settingsFrame.pack();
        settingsFrame.setVisible(true);//show settings frame
    }//GEN-LAST:event_settingsItemActionPerformed

    private void compButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compButtonActionPerformed
        // TODO add your handling code here:
        if(showComp==false)//check if comp is not showing
        {
            showComp=true;//set comp for showing
        }
        else
        {
            showComp=false;
        }
        ComputersAndContacts.showAndHideComp(showComp);//else hide comp
    }//GEN-LAST:event_compButtonActionPerformed

    private void clientMessengerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientMessengerButtonActionPerformed
        // TODO add your handling code here:
        if(ClientMessenger.connected==false)//checks for connection
        {
            JOptionPane.showMessageDialog(partnerPanel, "You are not connected!");
        }
        else
        {
            messengerClient.setVisible(true);//shows messenger
        }
        
    }//GEN-LAST:event_clientMessengerButtonActionPerformed

    private void serverMessengerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverMessengerButtonActionPerformed
        // TODO add your handling code here:
        if(ServerMessenger.connected==false)//check for connection
        {
            JOptionPane.showMessageDialog(partnerPanel, "You are not connected!");
        }
        else
        {
            messengerServer.setVisible(true);//shows messenger
        }
    }//GEN-LAST:event_serverMessengerButtonActionPerformed

    private void exitDialogueBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitDialogueBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitDialogueBoxActionPerformed

    private void settingsOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsOKButtonActionPerformed
         // TODO add your handling code here:
        try { //writing alias (changed/previously set) to file
            writeFile= new BufferedWriter(new FileWriter("alias.log"));
            writeFile.write(aliasField.getText());//writes from text field
            alias=aliasField.getText();//sets new alias if changed
            writeFile.close();
        }//end try 
        catch (IOException ex) {
            Logger.getLogger(RemoteDesktop.class.getName()).log(Level.SEVERE, null, ex);
        }//end catch

        try {//writes file dor checkbox check
            writeFile= new BufferedWriter(new FileWriter("exitDialogue.log"));
            if(exitDialogueBox.isSelected())
            {
                exitShow=true;
                writeFile.write("1");//writes 1 for selected
            }
            else
            {
                exitShow=false;
                writeFile.write("0");//writes 0 for deselected
            }
            writeFile.close();
        }//end try
        catch (IOException ex) {
            Logger.getLogger(RemoteDesktop.class.getName()).log(Level.SEVERE, null, ex);
        }//end catch
        
        try {//write white list contacts
            writeFile= new BufferedWriter(new FileWriter("whitelist.log"));
            writeFile.write(whiteListTextArea.getText());
            writeFile.close();
        }//end try
        catch (IOException ex) {
            Logger.getLogger(RemoteDesktop.class.getName()).log(Level.SEVERE, null, ex);
        }//end catch
        
        
         try {//write black list contacts
            writeFile= new BufferedWriter(new FileWriter("blacklist.log"));
            writeFile.write(blackListTextArea.getText());
            writeFile.close();
        }//end try
        catch (IOException ex) {
            Logger.getLogger(RemoteDesktop.class.getName()).log(Level.SEVERE, null, ex);
        }//end catch
        
        settingsFrame.setVisible(false);//settings frame hide
    }//GEN-LAST:event_settingsOKButtonActionPerformed

    private void exitCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitCheckBoxActionPerformed
        // TODO add your handling code here:
        if(exitCheckBox.isSelected())//check box from exit item
        {
            try {
                writeFile= new BufferedWriter(new FileWriter("exitDialogue.log"));
                writeFile.write("0");//writes file to set condition
                writeFile.close();
            }//end try 
            catch (IOException ex) {
                Logger.getLogger(RemoteDesktop.class.getName()).log(Level.SEVERE, null, ex);
            }//end catch
            exitShow=false;
        }//end if
    }//GEN-LAST:event_exitCheckBoxActionPerformed

    private void helpHelpItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpHelpItemActionPerformed
        // TODO add your handling code here:
        try
        {
            File helpFile=new File("Help.chm");
            Desktop.getDesktop().open(helpFile);//opens help file 
        }//end try
        catch(Exception ex)
        {
            ex.printStackTrace();
        }//end catch
    }//GEN-LAST:event_helpHelpItemActionPerformed

    private void aboutHelpItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutHelpItemActionPerformed
        // TODO add your handling code here:
        about.pack();
        about.setVisible(true);//shows about frame
    }//GEN-LAST:event_aboutHelpItemActionPerformed

    /**
     * @param args the command line arguments
     */
    //method setStatusTextArea() to set the connection status begin
    public static void setStatusTextArea(String status)
    {
        statusTextArea.setText(status);
    }//end method setStatusTextArea()
    
    //method dislayIP() to show IP address begin
    public void displayIP()
    {
        try
        {
            java.net.InetAddress i=java.net.InetAddress.getLocalHost();//get ip address
            ipTextArea.setText(i.getHostAddress());//show ip address is jtextfield
        }//end try
        catch(Exception exception)
        {
            ipTextArea.setText("IP not found");//showing if ip is not found
        }//end catch
    }//end method displayIP
    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoteDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoteDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoteDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoteDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /*
         * Create and display the form
         */ 
        
        
                
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new RemoteDesktop().setVisible(true);
            }
        });
        
        
        
    }//end main
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ExitDialog;
    private javax.swing.JFrame MainFrame;
    private javax.swing.JDialog about;
    private javax.swing.JMenuItem aboutHelpItem;
    private javax.swing.JTextField aliasField;
    private javax.swing.JLabel aliasLabel;
    private javax.swing.JPanel blackListPanel;
    private javax.swing.JTextArea blackListTextArea;
    private javax.swing.JButton cancelExitButton;
    private javax.swing.JButton clientMessengerButton;
    private javax.swing.JButton compButton;
    private javax.swing.JButton connectButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JCheckBox exitCheckBox;
    private javax.swing.JCheckBox exitDialogueBox;
    private javax.swing.JMenuItem exitFileItem;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JMenuItem helpHelpItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JTextArea ipTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBarMainFrame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel namePanel;
    private javax.swing.JMenu optionMenu;
    private javax.swing.JPanel partnerPanel;
    private javax.swing.JLabel portLabelYourInformation;
    private javax.swing.JTextField portTextFieldYourInformation;
    private javax.swing.JPopupMenu.Separator seperatorFileMenu;
    private javax.swing.JLabel serverIPLabelClient;
    private javax.swing.JTextField serverIPTextFieldClient;
    private javax.swing.JButton serverMessengerButton;
    private javax.swing.JLabel serverPortLabelClient;
    private javax.swing.JTextField serverPortTextFieldClient;
    private javax.swing.JButton setButtonYourInformation;
    private javax.swing.JFrame settingsFrame;
    private javax.swing.JMenuItem settingsItem;
    private javax.swing.JButton settingsOKButton;
    private javax.swing.JTabbedPane settingsPane;
    private static javax.swing.JTextArea statusTextArea;
    private javax.swing.JLabel userNameLabelYourInformation;
    private javax.swing.JPanel whiteListPanel;
    private javax.swing.JTextArea whiteListTextArea;
    private javax.swing.JPanel yourInformationPanel;
    // End of variables declaration//GEN-END:variables
}//end RemoteDesktop class
